name:                advent-of-code-y2021
version:             0.1.0.0
github:              "JSafieddine/advent-of-code-y2021"
license:             BSD3
author:              "Jamal Safieddine"
maintainer:          "mister.recursive@gmail.com"
copyright:           "2021 Jamal Safieddine"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/JSafieddine/advent-of-code-y2021#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - megaparsec
    - parser-combinators
    - vector
    - matrix 
    - hmatrix
    - containers
    - mtl

executables:
  advent-of-code-y2021-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - advent-of-code-y2021

tests:
  advent-of-code-y2021-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - advent-of-code-y2021
    - megaparsec
    - hspec
    - hspec-megaparsec
    - parser-combinators
    - containers
    - mtl
